# -*- coding: utf-8 -*-
"""Gradient Descent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sAvSBDTjLU_2ni_tbMTA09DdYnUDNC1x
"""

from __future__ import division, print_function, unicode_literals
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import animation
from IPython.display import HTML

np.random.seed(2)
X = np.random.rand(1000, 1)
y = 4 + 3 * X + 0.2 * np.random.randn(1000, 1)
Xbar = np.concatenate((np.ones((1000, 1)), X), axis=1)
w_exact = np.linalg.pinv(Xbar).dot(y)

def cost(w):
    N = Xbar.shape[0]
    return 0.5 / N * np.linalg.norm(y - Xbar.dot(w), 2)**2

def grad(w):
    N = Xbar.shape[0]
    return 1.0 / N * Xbar.T.dot(Xbar.dot(w) - y)

def myGD(w_init, eta):
    w = [w_init]
    for it in range(50):
        w_new = w[-1] - eta * grad(w[-1])
        w.append(w_new)
    return w

eta = 1
w_init = np.array([[2.0], [1.0]])
w_history = myGD(w_init, eta)

fig, ax = plt.subplots(figsize=(6, 5))

def update_left(i):
    ax.clear()
    ax.plot(X, y, 'b.', markersize=4)
    x0 = np.linspace(0, 1, 2)

    for j in range(i + 1):
        w_j = w_history[j]
        y0 = w_j[0] + w_j[1] * x0
        if j == i:
            ax.plot(x0, y0, 'r-', linewidth=2)
        else:
            ax.plot(x0, y0, 'r-', alpha=0.2)

    grad_norm = np.linalg.norm(grad(w_history[i]))

    ax.set_xlim([0.0, 1.0])
    ax.set_ylim([0.0, 10.0])
    ax.set_xlabel('x')
    ax.set_ylabel('y')
    ax.set_title(f"$\eta=$ {eta}; iter = {i}/49; $||grad||_2$ = {grad_norm:.3f}")

anim_left = animation.FuncAnimation(fig, update_left, frames=50, interval=150)
plt.close()

HTML(anim_left.to_html5_video())

A = np.linspace(1.5, 6.0, 100)
B = np.linspace(0.5, 4.5, 100)
W0, W1 = np.meshgrid(A, B)
Z = np.zeros_like(W0)

for i in range(W0.shape[0]):
    for j in range(W0.shape[1]):
        Z[i, j] = cost(np.array([[W0[i, j]], [W1[i, j]]]))

fig2, ax2 = plt.subplots(figsize=(6, 5))

def update_right(i):
    ax2.clear()
    CS = ax2.contour(W0, W1, Z, 30, colors='darkblue', linewidths=1)
    ax2.clabel(CS, inline=True, fontsize=8, fmt='%.3f')
    ax2.contourf(W0, W1, Z, 30, cmap='jet', alpha=0.3)

    w_hist_arr = np.array(w_history[:i+1]).squeeze()
    if i == 0:
        ax2.plot(w_hist_arr[0], w_hist_arr[1], 'ro', markersize=5)
    else:
        ax2.plot(w_hist_arr[:, 0], w_hist_arr[:, 1], 'r-o', markersize=5)

    ax2.plot(w_exact[0], w_exact[1], 'go', markersize=6)

    grad_norm = np.linalg.norm(grad(w_history[i]))

    ax2.set_xlim([1.5, 6.0])
    ax2.set_ylim([0.5, 4.5])
    ax2.set_xlabel('w0')
    ax2.set_ylabel('w1')
    ax2.set_title(f"$\eta=$ {eta}; iter = {i}/49; $||grad||_2$ = {grad_norm:.3f}")

anim_right = animation.FuncAnimation(fig2, update_right, frames=50, interval=150)
plt.close()

HTML(anim_right.to_html5_video())